# Generated by Django 4.0.4 on 2022-08-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cellNew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cell0', models.CharField(default='', max_length=100)),
                ('cell1', models.CharField(default='', max_length=100)),
                ('cell2', models.CharField(default='', max_length=100)),
                ('cell3', models.CharField(default='', max_length=100)),
                ('cell4', models.CharField(default='', max_length=100)),
                ('cell5', models.CharField(default='', max_length=100)),
                ('creationTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='heartNew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('beat', models.IntegerField()),
                ('creationTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='locationNew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gpsyear', models.CharField(default='', max_length=100)),
                ('gpsmonth', models.CharField(default='', max_length=100)),
                ('gpsday', models.CharField(default='', max_length=100)),
                ('gpshour', models.CharField(default='', max_length=100)),
                ('gpsmin', models.CharField(default='', max_length=100)),
                ('gpssec', models.CharField(default='', max_length=100)),
                ('gpscentisec', models.CharField(default='', max_length=100)),
                ('latdegree', models.CharField(default='', max_length=100)),
                ('latmin', models.CharField(default='', max_length=100)),
                ('latsec', models.CharField(default='', max_length=100)),
                ('lngdegree', models.CharField(default='', max_length=100)),
                ('lngmin', models.CharField(default='', max_length=100)),
                ('lngsec', models.CharField(default='', max_length=100)),
                ('gpsspeed', models.CharField(default='', max_length=100)),
                ('gpsheading', models.CharField(default='', max_length=100)),
                ('creationTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
